### ISSUE TITLE
NeoNFuscator ;)

### ISSUE THREAD

**Issue by NeoNCoding** [Mighty00/AutoriDeobfuscator#1]
It is NeoNFuscator :D and looks like it is broken because output of "AutotiDeobfuscator" is more confused than before and can't run

why are you trying it mighty? you can't crack it, you are big noobie for that..

Try cracking this with your AutoriDeobfuscator :smile:  :rofl: 
[YouAreBiggerNoobThanBefore.zip](https://github.com/Mighty00/AutoriDeobfuscator/files/2173758/YouAreBiggerNoobThanBefore.zip)

**Comment by Mighty00** [comment]
The output isn't broken. It works pretty fine

**Comment by NeoNCoding** [comment]
Send me

**Comment by Mighty00** [comment]
http://prntscr.com/k3x992
